/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Health */
        readonly get: operations["health_api_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/textbooks": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Textbooks */
        readonly get: operations["list_textbooks_api_textbooks_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/textbooks/upload": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Upload Textbook */
        readonly post: operations["upload_textbook_api_textbooks_upload_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/textbooks/upload-batch": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Upload Textbooks Batch */
        readonly post: operations["upload_textbooks_batch_api_textbooks_upload_batch_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/textbooks/{raw_file_id}/parse": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Parse Textbook */
        readonly post: operations["parse_textbook_api_textbooks__raw_file_id__parse_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/textbooks/{raw_file_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Textbook */
        readonly get: operations["get_textbook_api_textbooks__raw_file_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/uploads/sessions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Create Upload Session */
        readonly post: operations["create_upload_session_api_uploads_sessions_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/uploads/sessions/{session_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Upload Session */
        readonly get: operations["get_upload_session_api_uploads_sessions__session_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/uploads/sessions/{session_id}/chunks/{chunk_index}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Upload Chunk */
        readonly put: operations["upload_chunk_api_uploads_sessions__session_id__chunks__chunk_index__put"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/uploads/sessions/{session_id}/complete": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Complete Upload Session */
        readonly post: operations["complete_upload_session_api_uploads_sessions__session_id__complete_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/graph/build": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Build Graph */
        readonly post: operations["build_graph_api_graph_build_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/graph": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Graph */
        readonly get: operations["get_graph_api_graph_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/graph/nodes/{node_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Graph Node */
        readonly get: operations["get_graph_node_api_graph_nodes__node_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/jobs/{job_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Job */
        readonly get: operations["get_job_api_jobs__job_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorResponse */
        readonly ApiErrorResponse: {
            /** Message */
            readonly message: string;
            /** Code */
            readonly code: string;
            /** Detail */
            readonly detail?: string | null;
        };
        /** Body_upload_chunk_api_uploads_sessions__session_id__chunks__chunk_index__put */
        readonly Body_upload_chunk_api_uploads_sessions__session_id__chunks__chunk_index__put: {
            /** File */
            readonly file: string;
        };
        /** Body_upload_textbook_api_textbooks_upload_post */
        readonly Body_upload_textbook_api_textbooks_upload_post: {
            /** File */
            readonly file?: string | null;
            /** Files */
            readonly files?: readonly string[] | null;
            /** Textbook Title */
            readonly textbook_title?: string | null;
        };
        /** Body_upload_textbooks_batch_api_textbooks_upload_batch_post */
        readonly Body_upload_textbooks_batch_api_textbooks_upload_batch_post: {
            /** Files */
            readonly files: readonly string[];
            /** Textbook Title */
            readonly textbook_title?: string | null;
        };
        /** Chunk */
        readonly Chunk: {
            /** Id */
            readonly id: string;
            /** Raw File Id */
            readonly raw_file_id: string;
            /** Section Id */
            readonly section_id: string;
            /** Text */
            readonly text: string;
            /** Order Index */
            readonly order_index: number;
            /** Char Start */
            readonly char_start: number;
            /** Char End */
            readonly char_end: number;
            /** Char Count */
            readonly char_count: number;
            readonly source_locator: components["schemas"]["SourceLocator"];
            /** Metadata */
            readonly metadata?: {
                readonly [key: string]: unknown;
            };
        };
        /** DocumentElement */
        readonly DocumentElement: {
            /** Id */
            readonly id: string;
            /** Raw File Id */
            readonly raw_file_id: string;
            readonly type: components["schemas"]["DocumentElementType"];
            /** Text */
            readonly text: string;
            /** Order Index */
            readonly order_index: number;
            /** Parent Section Id */
            readonly parent_section_id?: string | null;
            readonly source_locator: components["schemas"]["SourceLocator"];
            /** Char Count */
            readonly char_count: number;
            /** Metadata */
            readonly metadata?: {
                readonly [key: string]: unknown;
            };
        };
        /**
         * DocumentElementType
         * @enum {string}
         */
        readonly DocumentElementType: "heading" | "paragraph" | "table" | "figure" | "list" | "page" | "slide" | "sheet" | "note";
        /** GraphBuildRequest */
        readonly GraphBuildRequest: {
            /** Raw File Id */
            readonly raw_file_id: string;
            /** Section Ids */
            readonly section_ids?: readonly string[];
            /**
             * Force Rebuild
             * @default false
             */
            readonly force_rebuild: boolean;
            /**
             * Max Sections
             * @default 20
             */
            readonly max_sections: number;
            /**
             * Max Nodes Per Section
             * @default 8
             */
            readonly max_nodes_per_section: number;
            /**
             * Use Llm
             * @default true
             */
            readonly use_llm: boolean;
        };
        /** GraphBuildResponse */
        readonly GraphBuildResponse: {
            readonly job: components["schemas"]["JobRecord"];
            /** Raw File Id */
            readonly raw_file_id: string;
            /** Graph Output Path */
            readonly graph_output_path: string;
            readonly graph: components["schemas"]["GraphResponse"];
        };
        /** GraphNodeDetailResponse */
        readonly GraphNodeDetailResponse: {
            readonly node: components["schemas"]["KnowledgeNode"];
            /** Edges */
            readonly edges?: readonly components["schemas"]["KnowledgeEdge"][];
            /** Evidence Chunks */
            readonly evidence_chunks?: readonly components["schemas"]["Chunk"][];
            /** Graph Id */
            readonly graph_id: string;
            /** Raw File Id */
            readonly raw_file_id: string;
        };
        /** GraphResponse */
        readonly GraphResponse: {
            /** Id */
            readonly id: string;
            /** Raw File Id */
            readonly raw_file_id: string;
            /** Title */
            readonly title: string;
            /** Nodes */
            readonly nodes: readonly components["schemas"]["KnowledgeNode"][];
            /** Edges */
            readonly edges: readonly components["schemas"]["KnowledgeEdge"][];
            /**
             * Generated At
             * Format: date-time
             */
            readonly generated_at?: string;
            /** Metadata */
            readonly metadata?: {
                readonly [key: string]: unknown;
            };
        };
        /** HealthResponse */
        readonly HealthResponse: {
            /**
             * Status
             * @constant
             */
            readonly status: "ok";
            /** App */
            readonly app: string;
            /** Version */
            readonly version: string;
            /**
             * Checked At
             * Format: date-time
             */
            readonly checked_at?: string;
        };
        /** JobRecord */
        readonly JobRecord: {
            /** Id */
            readonly id: string;
            readonly job_type: components["schemas"]["JobType"];
            readonly status: components["schemas"]["JobStatus"];
            /**
             * Progress
             * @default 0
             */
            readonly progress: number;
            /**
             * Message
             * @default
             */
            readonly message: string;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at?: string;
            /** Result */
            readonly result?: {
                readonly [key: string]: unknown;
            } | null;
            /** Error */
            readonly error?: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        readonly JobStatus: "queued" | "running" | "completed" | "failed";
        /**
         * JobType
         * @enum {string}
         */
        readonly JobType: "textbook_upload" | "textbook_batch_upload" | "textbook_parse" | "large_file_upload" | "graph_build" | "converted_textbook_import";
        /** KnowledgeEdge */
        readonly KnowledgeEdge: {
            /** Id */
            readonly id: string;
            /** Source Node Id */
            readonly source_node_id: string;
            /** Target Node Id */
            readonly target_node_id: string;
            readonly relation_type: components["schemas"]["KnowledgeRelationType"];
            /** Description */
            readonly description?: string | null;
            readonly source_locator: components["schemas"]["SourceLocator"];
            /** Evidence Chunk Ids */
            readonly evidence_chunk_ids?: readonly string[];
            /**
             * Confidence
             * @default 0
             */
            readonly confidence: number;
            /** Metadata */
            readonly metadata?: {
                readonly [key: string]: unknown;
            };
        };
        /** KnowledgeNode */
        readonly KnowledgeNode: {
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
            readonly node_type: components["schemas"]["KnowledgeNodeType"];
            /** Definition */
            readonly definition?: string | null;
            /** Aliases */
            readonly aliases?: readonly string[];
            readonly source_locator: components["schemas"]["SourceLocator"];
            /** Evidence Chunk Ids */
            readonly evidence_chunk_ids?: readonly string[];
            /**
             * Confidence
             * @default 0
             */
            readonly confidence: number;
            /** Metadata */
            readonly metadata?: {
                readonly [key: string]: unknown;
            };
        };
        /**
         * KnowledgeNodeType
         * @enum {string}
         */
        readonly KnowledgeNodeType: "Concept" | "Term" | "Mechanism" | "Process" | "Structure" | "Function" | "Disease" | "Symptom" | "Pathogen" | "Diagnosis" | "Treatment" | "Experiment" | "Example";
        /**
         * KnowledgeRelationType
         * @enum {string}
         */
        readonly KnowledgeRelationType: "ALIAS_OF" | "SAME_AS" | "IS_A" | "PART_OF" | "CONTAINS" | "PARALLEL_WITH" | "PREREQUISITE_OF" | "CAUSES" | "LEADS_TO" | "APPLIES_TO" | "CONTRASTS_WITH" | "EXPLAINS" | "EVIDENCED_BY" | "MENTIONED_IN" | "REFINES" | "CONFLICTS_WITH";
        /** ParsedTextbook */
        readonly ParsedTextbook: {
            /** Id */
            readonly id: string;
            readonly raw_file: components["schemas"]["RawFile"];
            /** Elements */
            readonly elements: readonly components["schemas"]["DocumentElement"][];
            /** Sections */
            readonly sections: readonly components["schemas"]["Section"][];
            /** Chunks */
            readonly chunks: readonly components["schemas"]["Chunk"][];
            /**
             * Generated At
             * Format: date-time
             */
            readonly generated_at?: string;
            /** Metadata */
            readonly metadata?: {
                readonly [key: string]: unknown;
            };
        };
        /** RawFile */
        readonly RawFile: {
            /** Id */
            readonly id: string;
            /** Original Filename */
            readonly original_filename: string;
            /** Title */
            readonly title: string;
            /** Format */
            readonly format: string;
            /**
             * Source Type
             * @default uploaded
             * @enum {string}
             */
            readonly source_type: "uploaded" | "converted_textbook" | "generated";
            /** Storage Path */
            readonly storage_path: string;
            /** Sha256 */
            readonly sha256: string;
            /** Size Bytes */
            readonly size_bytes: number;
            /** Page Count */
            readonly page_count?: number | null;
            /**
             * Text Char Count
             * @default 0
             */
            readonly text_char_count: number;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at?: string;
            /** Metadata */
            readonly metadata?: {
                readonly [key: string]: unknown;
            };
        };
        /** Section */
        readonly Section: {
            /** Id */
            readonly id: string;
            /** Raw File Id */
            readonly raw_file_id: string;
            /** Title */
            readonly title: string;
            /** @default section */
            readonly section_type: components["schemas"]["SectionType"];
            /**
             * Level
             * @default 1
             */
            readonly level: number;
            /** Order Index */
            readonly order_index: number;
            /** Parent Section Id */
            readonly parent_section_id?: string | null;
            /** Element Ids */
            readonly element_ids: readonly string[];
            /** Content */
            readonly content: string;
            /** Char Count */
            readonly char_count: number;
            readonly source_locator: components["schemas"]["SourceLocator"];
            /** Metadata */
            readonly metadata?: {
                readonly [key: string]: unknown;
            };
        };
        /**
         * SectionType
         * @enum {string}
         */
        readonly SectionType: "chapter" | "section" | "page_window" | "slide" | "sheet" | "table";
        /** SourceLocator */
        readonly SourceLocator: {
            /** Raw File Id */
            readonly raw_file_id: string;
            /** Source Path */
            readonly source_path: string;
            /** Source Type */
            readonly source_type: string;
            /** Locator Text */
            readonly locator_text: string;
            /** Page Start */
            readonly page_start?: number | null;
            /** Page End */
            readonly page_end?: number | null;
            /** Line Start */
            readonly line_start?: number | null;
            /** Line End */
            readonly line_end?: number | null;
            /** Sheet Name */
            readonly sheet_name?: string | null;
            /** Row Start */
            readonly row_start?: number | null;
            /** Row End */
            readonly row_end?: number | null;
            /** Slide Number */
            readonly slide_number?: number | null;
            /** Char Start */
            readonly char_start?: number | null;
            /** Char End */
            readonly char_end?: number | null;
            /** Element Ids */
            readonly element_ids?: readonly string[];
            /** Quote Hash */
            readonly quote_hash?: string | null;
        };
        /** TextbookBatchUploadResponse */
        readonly TextbookBatchUploadResponse: {
            readonly job: components["schemas"]["JobRecord"];
            /** Items */
            readonly items: readonly components["schemas"]["TextbookUploadResponse"][];
            /** Errors */
            readonly errors?: readonly components["schemas"]["TextbookUploadError"][];
            /** Total Count */
            readonly total_count: number;
            /** Success Count */
            readonly success_count: number;
            /** Failed Count */
            readonly failed_count: number;
        };
        /** TextbookListResponse */
        readonly TextbookListResponse: {
            /** Textbooks */
            readonly textbooks: readonly components["schemas"]["TextbookSummary"][];
        };
        /** TextbookSummary */
        readonly TextbookSummary: {
            /** Raw File Id */
            readonly raw_file_id: string;
            /** Title */
            readonly title: string;
            /** Format */
            readonly format: string;
            /** Page Count */
            readonly page_count?: number | null;
            /** Element Count */
            readonly element_count: number;
            /** Section Count */
            readonly section_count: number;
            /** Chunk Count */
            readonly chunk_count: number;
            /** Parsed Output Path */
            readonly parsed_output_path: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** TextbookUploadError */
        readonly TextbookUploadError: {
            /** Filename */
            readonly filename: string;
            /** Error */
            readonly error: string;
            readonly job?: components["schemas"]["JobRecord"] | null;
        };
        /** TextbookUploadResponse */
        readonly TextbookUploadResponse: {
            readonly job: components["schemas"]["JobRecord"];
            /** Raw File Id */
            readonly raw_file_id: string;
            /** Parsed Output Path */
            readonly parsed_output_path: string;
            readonly parsed_textbook: components["schemas"]["ParsedTextbook"];
        };
        /** UploadChunkResponse */
        readonly UploadChunkResponse: {
            readonly session: components["schemas"]["UploadSessionRecord"];
            /** Chunk Index */
            readonly chunk_index: number;
            /** Received Bytes */
            readonly received_bytes: number;
        };
        /** UploadSessionCompleteResponse */
        readonly UploadSessionCompleteResponse: {
            readonly session: components["schemas"]["UploadSessionRecord"];
            readonly job: components["schemas"]["JobRecord"];
            readonly parsed_upload?: components["schemas"]["TextbookUploadResponse"] | null;
        };
        /** UploadSessionCreateRequest */
        readonly UploadSessionCreateRequest: {
            /** Filename */
            readonly filename: string;
            /** Total Size Bytes */
            readonly total_size_bytes: number;
            /** Total Chunks */
            readonly total_chunks: number;
            /** Chunk Size Bytes */
            readonly chunk_size_bytes: number;
            /** Sha256 */
            readonly sha256?: string | null;
            /** Content Type */
            readonly content_type?: string | null;
            /**
             * Parse On Complete
             * @default true
             */
            readonly parse_on_complete: boolean;
        };
        /** UploadSessionRecord */
        readonly UploadSessionRecord: {
            /** Id */
            readonly id: string;
            /** Filename */
            readonly filename: string;
            /** Total Size Bytes */
            readonly total_size_bytes: number;
            /** Total Chunks */
            readonly total_chunks: number;
            /** Chunk Size Bytes */
            readonly chunk_size_bytes: number;
            /** Sha256 */
            readonly sha256?: string | null;
            /** Content Type */
            readonly content_type?: string | null;
            /**
             * Parse On Complete
             * @default true
             */
            readonly parse_on_complete: boolean;
            /** @default created */
            readonly status: components["schemas"]["UploadSessionStatus"];
            /** Uploaded Chunks */
            readonly uploaded_chunks?: readonly number[];
            /** Missing Chunks */
            readonly missing_chunks?: readonly number[];
            /**
             * Received Bytes
             * @default 0
             */
            readonly received_bytes: number;
            /**
             * Upload Progress
             * @default 0
             */
            readonly upload_progress: number;
            /**
             * Parse Progress
             * @default 0
             */
            readonly parse_progress: number;
            /** Job Id */
            readonly job_id?: string | null;
            /** Assembled Path */
            readonly assembled_path?: string | null;
            /** Raw File Id */
            readonly raw_file_id?: string | null;
            /** Parsed Output Path */
            readonly parsed_output_path?: string | null;
            /** Error */
            readonly error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at?: string;
        };
        /**
         * UploadSessionStatus
         * @enum {string}
         */
        readonly UploadSessionStatus: "created" | "uploading" | "assembling" | "parsing" | "completed" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly health_api_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly list_textbooks_api_textbooks_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TextbookListResponse"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly upload_textbook_api_textbooks_upload_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "multipart/form-data": components["schemas"]["Body_upload_textbook_api_textbooks_upload_post"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TextbookUploadResponse"] | components["schemas"]["TextbookBatchUploadResponse"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly upload_textbooks_batch_api_textbooks_upload_batch_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": components["schemas"]["Body_upload_textbooks_batch_api_textbooks_upload_batch_post"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TextbookBatchUploadResponse"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly parse_textbook_api_textbooks__raw_file_id__parse_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly raw_file_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TextbookUploadResponse"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly get_textbook_api_textbooks__raw_file_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly raw_file_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ParsedTextbook"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly create_upload_session_api_uploads_sessions_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UploadSessionCreateRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UploadSessionRecord"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly get_upload_session_api_uploads_sessions__session_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UploadSessionRecord"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly upload_chunk_api_uploads_sessions__session_id__chunks__chunk_index__put: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
                readonly chunk_index: number;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": components["schemas"]["Body_upload_chunk_api_uploads_sessions__session_id__chunks__chunk_index__put"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UploadChunkResponse"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly complete_upload_session_api_uploads_sessions__session_id__complete_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UploadSessionCompleteResponse"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly build_graph_api_graph_build_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["GraphBuildRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GraphBuildResponse"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly get_graph_api_graph_get: {
        readonly parameters: {
            readonly query?: {
                readonly mode?: "single";
                readonly raw_file_id?: string | null;
                readonly top_n?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly get_graph_node_api_graph_nodes__node_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly node_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["GraphNodeDetailResponse"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    readonly get_job_api_jobs__job_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly job_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Bad Request */
            readonly 400: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
