/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/textbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Textbooks */
        get: operations["list_textbooks_api_textbooks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/textbooks/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Textbook */
        post: operations["upload_textbook_api_textbooks_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/textbooks/upload-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Textbooks Batch */
        post: operations["upload_textbooks_batch_api_textbooks_upload_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/textbooks/upload-async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Textbook Async */
        post: operations["upload_textbook_async_api_textbooks_upload_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/textbooks/{raw_file_id}/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Textbook */
        post: operations["parse_textbook_api_textbooks__raw_file_id__parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/textbooks/{raw_file_id}/parse-async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Textbook Async */
        post: operations["parse_textbook_async_api_textbooks__raw_file_id__parse_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/textbooks/{raw_file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Textbook */
        get: operations["get_textbook_api_textbooks__raw_file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload Session */
        post: operations["create_upload_session_api_uploads_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upload Session */
        get: operations["get_upload_session_api_uploads_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/sessions/{session_id}/chunks/{chunk_index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Chunk */
        put: operations["upload_chunk_api_uploads_sessions__session_id__chunks__chunk_index__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Upload Session */
        post: operations["complete_upload_session_api_uploads_sessions__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/sessions/{session_id}/complete-async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Upload Session Async */
        post: operations["complete_upload_session_async_api_uploads_sessions__session_id__complete_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Graph */
        post: operations["build_graph_api_graph_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/nodes/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph Node */
        get: operations["get_graph_node_api_graph_nodes__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorResponse */
        ApiErrorResponse: {
            /** Message */
            message: string;
            /** Code */
            code: string;
            /** Detail */
            detail?: string | null;
        };
        /** AsyncTextbookParseResponse */
        AsyncTextbookParseResponse: {
            job: components["schemas"]["JobRecord"];
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
            /** Upload Session Id */
            upload_session_id?: string | null;
        };
        /** Body_upload_chunk_api_uploads_sessions__session_id__chunks__chunk_index__put */
        Body_upload_chunk_api_uploads_sessions__session_id__chunks__chunk_index__put: {
            /** File */
            file: string;
        };
        /** Body_upload_textbook_api_textbooks_upload_post */
        Body_upload_textbook_api_textbooks_upload_post: {
            /** File */
            file?: string | null;
            /** Files */
            files?: string[] | null;
            /** Textbook Title */
            textbook_title?: string | null;
        };
        /** Body_upload_textbook_async_api_textbooks_upload_async_post */
        Body_upload_textbook_async_api_textbooks_upload_async_post: {
            /** File */
            file?: string | null;
            /** Textbook Title */
            textbook_title?: string | null;
        };
        /** Body_upload_textbooks_batch_api_textbooks_upload_batch_post */
        Body_upload_textbooks_batch_api_textbooks_upload_batch_post: {
            /** Files */
            files: string[];
            /** Textbook Title */
            textbook_title?: string | null;
        };
        /** Chunk */
        Chunk: {
            /** Id */
            id: string;
            /** Raw File Id */
            raw_file_id: string;
            /** Section Id */
            section_id: string;
            /** Text */
            text: string;
            /** Order Index */
            order_index: number;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Char Count */
            char_count: number;
            source_locator: components["schemas"]["SourceLocator"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** DocumentElement */
        DocumentElement: {
            /** Id */
            id: string;
            /** Raw File Id */
            raw_file_id: string;
            type: components["schemas"]["DocumentElementType"];
            /** Text */
            text: string;
            /** Order Index */
            order_index: number;
            /** Parent Section Id */
            parent_section_id?: string | null;
            source_locator: components["schemas"]["SourceLocator"];
            /** Char Count */
            char_count: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * DocumentElementType
         * @enum {string}
         */
        DocumentElementType: "heading" | "paragraph" | "table" | "figure" | "list" | "page" | "slide" | "sheet" | "note";
        /** GraphBuildRequest */
        GraphBuildRequest: {
            /** Raw File Id */
            raw_file_id: string;
            /** Section Ids */
            section_ids?: string[];
            /**
             * Force Rebuild
             * @default false
             */
            force_rebuild: boolean;
            /**
             * Max Sections
             * @default 20
             */
            max_sections: number;
            /**
             * Max Nodes Per Section
             * @default 8
             */
            max_nodes_per_section: number;
            /**
             * Use Llm
             * @default true
             */
            use_llm: boolean;
        };
        /** GraphBuildResponse */
        GraphBuildResponse: {
            job: components["schemas"]["JobRecord"];
            /** Raw File Id */
            raw_file_id: string;
            /** Graph Output Path */
            graph_output_path: string;
            graph: components["schemas"]["GraphResponse"];
        };
        /** GraphNodeDetailResponse */
        GraphNodeDetailResponse: {
            node: components["schemas"]["KnowledgeNode"];
            /** Edges */
            edges?: components["schemas"]["KnowledgeEdge"][];
            /** Evidence Chunks */
            evidence_chunks?: components["schemas"]["Chunk"][];
            /** Graph Id */
            graph_id: string;
            /** Raw File Id */
            raw_file_id: string;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Id */
            id: string;
            /** Raw File Id */
            raw_file_id: string;
            /** Title */
            title: string;
            /** Nodes */
            nodes: components["schemas"]["KnowledgeNode"][];
            /** Edges */
            edges: components["schemas"]["KnowledgeEdge"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** App */
            app: string;
            /** Version */
            version: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at?: string;
        };
        /** JobRecord */
        JobRecord: {
            /** Id */
            id: string;
            job_type: components["schemas"]["JobType"];
            status: components["schemas"]["JobStatus"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Steps */
            steps?: components["schemas"]["PipelineStepRecord"][];
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /** Context Path */
            context_path?: string | null;
        };
        /** JobRetryResponse */
        JobRetryResponse: {
            job: components["schemas"]["JobRecord"];
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "completed" | "failed";
        /**
         * JobType
         * @enum {string}
         */
        JobType: "textbook_upload" | "textbook_batch_upload" | "textbook_parse" | "textbook_pipeline" | "large_file_upload" | "graph_build" | "converted_textbook_import";
        /** KnowledgeEdge */
        KnowledgeEdge: {
            /** Id */
            id: string;
            /** Source Node Id */
            source_node_id: string;
            /** Target Node Id */
            target_node_id: string;
            relation_type: components["schemas"]["KnowledgeRelationType"];
            /** Description */
            description?: string | null;
            source_locator: components["schemas"]["SourceLocator"];
            /** Evidence Chunk Ids */
            evidence_chunk_ids?: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** KnowledgeNode */
        KnowledgeNode: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            node_type: components["schemas"]["KnowledgeNodeType"];
            /** Definition */
            definition?: string | null;
            /** Aliases */
            aliases?: string[];
            source_locator: components["schemas"]["SourceLocator"];
            /** Evidence Chunk Ids */
            evidence_chunk_ids?: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * KnowledgeNodeType
         * @enum {string}
         */
        KnowledgeNodeType: "Concept" | "Term" | "Mechanism" | "Process" | "Structure" | "Function" | "Disease" | "Symptom" | "Pathogen" | "Diagnosis" | "Treatment" | "Experiment" | "Example";
        /**
         * KnowledgeRelationType
         * @enum {string}
         */
        KnowledgeRelationType: "ALIAS_OF" | "SAME_AS" | "IS_A" | "PART_OF" | "CONTAINS" | "PARALLEL_WITH" | "PREREQUISITE_OF" | "CAUSES" | "LEADS_TO" | "APPLIES_TO" | "CONTRASTS_WITH" | "EXPLAINS" | "EVIDENCED_BY" | "MENTIONED_IN" | "REFINES" | "CONFLICTS_WITH";
        /** ParsedTextbook */
        ParsedTextbook: {
            /** Id */
            id: string;
            raw_file: components["schemas"]["RawFile"];
            /** Elements */
            elements: components["schemas"]["DocumentElement"][];
            /** Sections */
            sections: components["schemas"]["Section"][];
            /** Chunks */
            chunks: components["schemas"]["Chunk"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * PipelineStepName
         * @enum {string}
         */
        PipelineStepName: "assemble_file" | "detect_format" | "parse_elements" | "build_sections" | "chunk_sections" | "persist_parsed";
        /** PipelineStepRecord */
        PipelineStepRecord: {
            name: components["schemas"]["PipelineStepName"];
            /** @default queued */
            status: components["schemas"]["PipelineStepStatus"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * PipelineStepStatus
         * @enum {string}
         */
        PipelineStepStatus: "queued" | "running" | "completed" | "failed" | "skipped";
        /** RawFile */
        RawFile: {
            /** Id */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Title */
            title: string;
            /** Format */
            format: string;
            /**
             * Source Type
             * @default uploaded
             * @enum {string}
             */
            source_type: "uploaded" | "converted_textbook" | "generated";
            /** Storage Path */
            storage_path: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Page Count */
            page_count?: number | null;
            /**
             * Text Char Count
             * @default 0
             */
            text_char_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** Section */
        Section: {
            /** Id */
            id: string;
            /** Raw File Id */
            raw_file_id: string;
            /** Title */
            title: string;
            /** @default section */
            section_type: components["schemas"]["SectionType"];
            /**
             * Level
             * @default 1
             */
            level: number;
            /** Order Index */
            order_index: number;
            /** Parent Section Id */
            parent_section_id?: string | null;
            /** Element Ids */
            element_ids: string[];
            /** Content */
            content: string;
            /** Char Count */
            char_count: number;
            source_locator: components["schemas"]["SourceLocator"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * SectionType
         * @enum {string}
         */
        SectionType: "chapter" | "section" | "page_window" | "slide" | "sheet" | "table";
        /** SourceLocator */
        SourceLocator: {
            /** Raw File Id */
            raw_file_id: string;
            /** Source Path */
            source_path: string;
            /** Source Type */
            source_type: string;
            /** Locator Text */
            locator_text: string;
            /** Page Start */
            page_start?: number | null;
            /** Page End */
            page_end?: number | null;
            /** Line Start */
            line_start?: number | null;
            /** Line End */
            line_end?: number | null;
            /** Sheet Name */
            sheet_name?: string | null;
            /** Row Start */
            row_start?: number | null;
            /** Row End */
            row_end?: number | null;
            /** Slide Number */
            slide_number?: number | null;
            /** Char Start */
            char_start?: number | null;
            /** Char End */
            char_end?: number | null;
            /** Element Ids */
            element_ids?: string[];
            /** Quote Hash */
            quote_hash?: string | null;
        };
        /** TextbookBatchUploadResponse */
        TextbookBatchUploadResponse: {
            job: components["schemas"]["JobRecord"];
            /** Items */
            items: components["schemas"]["TextbookUploadResponse"][];
            /** Errors */
            errors?: components["schemas"]["TextbookUploadError"][];
            /** Total Count */
            total_count: number;
            /** Success Count */
            success_count: number;
            /** Failed Count */
            failed_count: number;
        };
        /** TextbookListResponse */
        TextbookListResponse: {
            /** Textbooks */
            textbooks: components["schemas"]["TextbookSummary"][];
        };
        /** TextbookSummary */
        TextbookSummary: {
            /** Raw File Id */
            raw_file_id: string;
            /** Title */
            title: string;
            /** Format */
            format: string;
            /** Page Count */
            page_count?: number | null;
            /** Element Count */
            element_count: number;
            /** Section Count */
            section_count: number;
            /** Chunk Count */
            chunk_count: number;
            /** Parsed Output Path */
            parsed_output_path: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TextbookUploadError */
        TextbookUploadError: {
            /** Filename */
            filename: string;
            /** Error */
            error: string;
            job?: components["schemas"]["JobRecord"] | null;
        };
        /** TextbookUploadResponse */
        TextbookUploadResponse: {
            job: components["schemas"]["JobRecord"];
            /** Raw File Id */
            raw_file_id: string;
            /** Parsed Output Path */
            parsed_output_path: string;
            parsed_textbook: components["schemas"]["ParsedTextbook"];
        };
        /** UploadChunkResponse */
        UploadChunkResponse: {
            session: components["schemas"]["UploadSessionRecord"];
            /** Chunk Index */
            chunk_index: number;
            /** Received Bytes */
            received_bytes: number;
        };
        /** UploadSessionCompleteResponse */
        UploadSessionCompleteResponse: {
            session: components["schemas"]["UploadSessionRecord"];
            job: components["schemas"]["JobRecord"];
            parsed_upload?: components["schemas"]["TextbookUploadResponse"] | null;
        };
        /** UploadSessionCreateRequest */
        UploadSessionCreateRequest: {
            /** Filename */
            filename: string;
            /** Total Size Bytes */
            total_size_bytes: number;
            /** Total Chunks */
            total_chunks: number;
            /** Chunk Size Bytes */
            chunk_size_bytes: number;
            /** Sha256 */
            sha256?: string | null;
            /** Content Type */
            content_type?: string | null;
            /**
             * Parse On Complete
             * @default true
             */
            parse_on_complete: boolean;
        };
        /** UploadSessionRecord */
        UploadSessionRecord: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Total Size Bytes */
            total_size_bytes: number;
            /** Total Chunks */
            total_chunks: number;
            /** Chunk Size Bytes */
            chunk_size_bytes: number;
            /** Sha256 */
            sha256?: string | null;
            /** Content Type */
            content_type?: string | null;
            /**
             * Parse On Complete
             * @default true
             */
            parse_on_complete: boolean;
            /** @default created */
            status: components["schemas"]["UploadSessionStatus"];
            /** Uploaded Chunks */
            uploaded_chunks?: number[];
            /** Missing Chunks */
            missing_chunks?: number[];
            /**
             * Received Bytes
             * @default 0
             */
            received_bytes: number;
            /**
             * Upload Progress
             * @default 0
             */
            upload_progress: number;
            /**
             * Parse Progress
             * @default 0
             */
            parse_progress: number;
            /** Job Id */
            job_id?: string | null;
            /** Assembled Path */
            assembled_path?: string | null;
            /** Raw File Id */
            raw_file_id?: string | null;
            /** Parsed Output Path */
            parsed_output_path?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * UploadSessionStatus
         * @enum {string}
         */
        UploadSessionStatus: "created" | "uploading" | "assembling" | "parsing" | "completed" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_textbooks_api_textbooks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextbookListResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    upload_textbook_api_textbooks_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_textbook_api_textbooks_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextbookUploadResponse"] | components["schemas"]["TextbookBatchUploadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    upload_textbooks_batch_api_textbooks_upload_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_textbooks_batch_api_textbooks_upload_batch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextbookBatchUploadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    upload_textbook_async_api_textbooks_upload_async_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_textbook_async_api_textbooks_upload_async_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncTextbookParseResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    parse_textbook_api_textbooks__raw_file_id__parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                raw_file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextbookUploadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    parse_textbook_async_api_textbooks__raw_file_id__parse_async_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                raw_file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncTextbookParseResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_textbook_api_textbooks__raw_file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                raw_file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedTextbook"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create_upload_session_api_uploads_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionRecord"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_upload_session_api_uploads_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionRecord"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    upload_chunk_api_uploads_sessions__session_id__chunks__chunk_index__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                chunk_index: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_chunk_api_uploads_sessions__session_id__chunks__chunk_index__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadChunkResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    complete_upload_session_api_uploads_sessions__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionCompleteResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    complete_upload_session_async_api_uploads_sessions__session_id__complete_async_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncTextbookParseResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    build_graph_api_graph_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphBuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphBuildResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_graph_api_graph_get: {
        parameters: {
            query?: {
                mode?: "single";
                raw_file_id?: string | null;
                top_n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_graph_node_api_graph_nodes__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphNodeDetailResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    retry_job_api_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRetryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
